<?php

namespace app\modules\admin\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property int $category_product_id
 * @property string $title
 * @property string $content
 * @property float $price
 * @property float $old_price
 * @property string|null $description
 * @property string|null $keywords
 * @property string $img
 * @property int $is_offer
 * @property int $gift
 */
class Product extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
//            [['category_id', 'category_product_id', 'title', 'content', 'is_offer', 'gift'], 'required'],
            [['category_id', 'title', 'content', 'is_offer', 'gift'], 'required'],
//            [['category_id', 'category_product_id', 'is_offer', 'gift'], 'integer'],
            [['category_id', 'is_offer', 'gift'], 'integer'],
            [['content'], 'string'],
            [['visible'], 'safe'],
            [['price', 'old_price'], 'number'],
            [['price', 'old_price'], 'default', 'value' => 0],
            [['img'], 'default', 'value' => 'images/no-image.png'],
            [['title', 'description', 'keywords', 'img'], 'string', 'max' => 255],
//            [['file'], 'image'],
        ];

    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
//            'category_product_id' => 'Category Product ID',
            'title' => 'Наименование',
            'content' => 'Content',
            'price' => 'Цена',
            'old_price' => 'Старая цена',
            'description' => 'Описание',
            'keywords' => 'Ключевые слова',
            'img' => 'Фото',
            'file' => 'Фото',
            'is_offer' => 'Акция',
            'gift' => 'Подарок',
            'visible' => 'Показывать',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $dir='images/' . date("Y-m-d") . '/';
            if (!is_dir($dir)){
                mkdir($dir);
            }
            $file_name=uniqid() . '_' . $file->baseName . '.' . $file->extension;
            $this->img=$dir . $file_name;
            $file->saveAs($this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
